### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by gbonnefille** [einoj/esa-beamer#1]
I'm interested in contributing to your ESA style for beamer.

Can you add a license information for your job, please?

PS: My production process is based on MarkDown processed by Pandoc.

**Comment by einoj** [comment]
Sure, but I'll have to contact https://github.com/icot/cern-beamer first since this theme is based on theirs.

Pandoc looks interesting, I've always just used pdflatex.

PS: Are you a YGT at ESA?

**Comment by einoj** [comment]
Added MIT license. Remember that this is for the TEX code and not for the logos, as those are copyrighted by ESA
